### ISSUE TITLE
Unable (or just very slow) to launch minminguard GUI

### ISSUE THREAD

**Issue by kennethho** [chiehmin/MinMinGuard#109]
I am running CM11 (kitkat) on OnePlus One. Had been experiencing very slow loading of minminguard GUI (apps list) similar to issue #101 since early versions of 2.0 alphas. I never timed it, it felt like 2~3 minutes.

With the latest alpha, 2.0 alpha14, I am unable to launch its GUI at all. I waited ~5 minutes, the GUI seemed to be still loading. I am not sure if it would launch if I had more patient.

I've rolled back and currently on 1.9.0, things are working fine. However, as a long time user, I really hate to miss your latest feature - auto + black list.

Please let me know if you are interested in looking into this issue. I would provide more info and logs upon request.

Cheers.

**Comment by valzi** [comment]
I have the same issue. It's not usable for me.
