### ISSUE TITLE
MinMinGuard doesn't remove ad space

### ISSUE THREAD

**Issue by christantoan** [chiehmin/MinMinGuard#142]
App name: pixiv

Store link: https://play.google.com/store/apps/details?id=jp.pxv.android&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dpixiv+google+play&pcampaignid=APPU_1_zlogWKSuIMSqa7LWvcAN

Page: Gallery page

**Comment by christantoan** [comment]
Since updated to v2, MinMinGuard no longer remove the add space

**Comment by jawz101** [comment]
Same issue with Hill Climb Racing game.

I went ahead and disabled com.fingersoft.hillclimb/com.google.android.gms.ads.AdActivity using My Android Tools Pro.  I get a banner placeholder with an error msg that the app manifest can't find the adactivity but at least no ad is shown

**Comment by MSkjel** [comment]
Fixed as of https://github.com/chiehmin/MinMinGuard/commit/500d872984ba961b180ea699f6940da05d4517bb
