### ISSUE TITLE
[Question] Does MinMinGuard require internet access? 

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [chiehmin/MinMinGuard#144]
Hi there,

I'm trying to figure out if MinMinGuard needs internet access, for example, to fetch a dynamic list of ads to block?

Or does MinMinGuard's list (if it has one) get updated only with the application its self? 

Thanks

**Comment by ckuethe** [comment]
Internet access is not strictly necessary - it seems to be used for crash reports - but the app functions properly without it. 

The ad library overrides are compiled into  minminguard, and are only updated when the application is updated.
