### ISSUE TITLE
Doesn't support YouTube ads anymore.

### ISSUE THREAD

**Issue by acsway878787** [chiehmin/MinMinGuard#150]
Like I metioned above, the ads in YouTube starts showing again.

**Comment by aviraxp** [comment]
Use YouTube AdAway.

**Comment by acsway878787** [comment]
@aviraxp But YouTube AdAway doesn't work anymore, because the developer stops updating.
That's why I'm finding alternatives.
Thanks for your reply!

**Comment by selvodka** [comment]
@aviraxp i use https://github.com/ram-on/SkyTube or https://github.com/TeamNewPipe/NewPipe to watch youtube w/o ads
