### ISSUE TITLE
Add broadcast receiver to reduce battery use

### ISSUE THREAD

**Issue by hadiarajesh** [chiehmin/MinMinGuard#152]
In the current version of min min guard, it always runs in background to detect advertisement which uses more battery. I want to suggest the use of broadcast receiver. What I want to say is app only show advertisement when device connect to internet.so you can use data connection broadcast receiver to start minmin guard service and stop the service when data is disconnected.this will reduce battery use.
Thanks

**Comment by MSkjel** [comment]
It doesnt run in the background to detect ads. It hooks the methods used for adloading or displaying ads in any app
