### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by RenTec** [chiehmin/MinMinGuard#165]
Unknown sources is enabled, verify applications disabled. Installer says failed

Logcat: 06-12 21:29:41.634 E/PackageParser(1089): Package tw.fatminmin.xposed.minminguard has no certificates at entry AndroidManifest.xml; ignoring!

I should note that I am using Android 4.4.2

**Comment by leo-liar** [comment]
Got the same error as well (Oneplus One with [**Sultanxda's CyanogenMod 13.0**][1]). Unknown sources enabled, verify applications and signature checks disabled.

Installer also throws _Error code: -103_ which might be related to [**this issue**][2] about older devices not being able to recognize packages that were signed using SHA256 hash functions.

[1]: https://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-cyanogenmod-13-0-t3242700 "[EOL][ROM+KERNEL][6.0.1] Unofficial CyanogenMod 13.0 with 3.4.0 kernel [Apr 30, 2017]"
[2]: https://stackoverflow.com/questions/33149140/play-store-cant-install-app-error-code-103 "Play Store: Can't install app, (Error code: -103)"

**Comment by marceleira** [comment]
Got same error on v2.0.1
v2.0.1a1 looks fine
Details:
```
$ adb install MinMinGuard.apk 
MinMinGuard.apk: 1 file pushed. 4.7 MB/s (2412010 bytes in 0.487s)
	pkg: /data/local/tmp/MinMinGuard.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
```

**Comment by chiehmin** [comment]
The difference between this build and last successfull build are

1. I add cache in my .travis.yml
2. I request for debug build previously

Thanks


Marcelo Assis <notifications@github.com> 於 2018年6月14日 週四 上午12:01 寫道：

**Comment by chiehmin** [comment]
Sorry, I thought I was replying to the travis-ci support. I was replying to the wrong email ><.

**Comment by chiehmin** [comment]
I will look into the signature issue later

**Comment by chiehmin** [comment]
Seems like I did not check the version 1 signature in v2.0.1 release. I will check it in the future releases.
![screenshot from 2018-06-24 15-13-06](https://user-images.githubusercontent.com/1941281/41816820-2e5ca584-77c1-11e8-9ed5-34075a1d9cd4.png)
