### ISSUE TITLE
Version 2.0.2 instable

### ISSUE THREAD

**Issue by JohnChu101** [chiehmin/MinMinGuard#169]
In many app i found the ads reappearing. But my MinMinGuard is turned on in Xposed Framework.
I opened MinMinGuard and the ad filter for those apps are on too.
But after checking that, when i reopen the apps, the ads are gone.
This situation can be applied to many apps, so i wont list here. And there was no such problem in version 2.0.1.

**Comment by MSkjel** [comment]
The issue has been fixed with [https://github.com/MSkjel/MinMinGuard/commit/25c2859c41d1695a688e606c22c2b1ab39b14648](url). Just waiting for him to accept my pull request.
