### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [chiehmin/MinMinGuard#174]
Hi,

Since this app is GNU GPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by MSkjel** [comment]
It's released in the Xposed Repository

**Comment by Poussinou** [comment]
We at F-Droid could package this app for F-Droid by ourselves, we just need your agreement, but choice is yours.
