### ISSUE TITLE
Applovin and appnext support

### ISSUE THREAD

**Issue by Kilroy93** [chiehmin/MinMinGuard#175]
Hi, I'd suggest to also include appnext and applovin for the ad blocking.

Appnext: https://www.appnext.com
Applovin: https://www.applovin.com

I found both of them in this App http://tvtap.net/download.php

Thanks.

**Comment by MSkjel** [comment]
It would be an understatement to say this app is full of ads. Ads no longer show up as of [pull 177](https://github.com/chiehmin/MinMinGuard/pull/177).

Here is a list of all ad networks in this app:

Detected networks:
AdColony - 3.2.1
UnityAds - 2.2.1
MoPub - 5.5.0
Chartboost - 7.2.1
IronSource - 6.7.10
Ogury - 3.0.36-moat
Tapjoy - 11.12.2
Vungle - 6.3.24
AppNext - 2.3.1.471
AerServ - 3.1.1
DoubleClick - 12451000
Amazon - amznAdSDK-android-5.8.2-dev
Facebook - 5.1.0
AdMob - 12451000
AppLovin - 9.2.1
