### ISSUE TITLE
Doesn't work after version "v0.4.6.2 (4529) (SandHook)" of edXposed with latest version of MinMinGuard(2.1.1)

### ISSUE THREAD

**Issue by Kara-ism** [chiehmin/MinMinGuard#194]
Hi, FatMinMin
I appreciate for your great work, and it's truly a great moudle!! :)

However, it has been down for several releases of edXposed, which can't hide advertisements anymore! :(

Such as JPTT, it starts to show ads again.
![Screenshot_20200511-031937116](https://user-images.githubusercontent.com/9511279/81508604-99245180-9337-11ea-85c2-ce156b8e26b0.jpg)

I wish this great moudle will not be abandoned.
Regards! :)

Version of MinMinGuard Tested : 2.0.9/2.1.1
Version of Android : ZENFONE 6(2019)/Android Pie Official
Version of edXposed Tested : "v0.4.6.2 (4529) (SandHook)" and "EdXposed-SandHook-v0.5.0.0 (4548)-release", both of them are not worked.

**Comment by MSkjel** [comment]
Could you leave a link for the apk? Does it happen on all apps? Does MinMinGuard report any ad-network for the app?

**Comment by Kara-ism** [comment]
> Could you leave a link for the apk? Does it happen on all apps? Does MinMinGuard report any ad-network for the app?

This invalid situation occurs on all Apps.

You can get this app from the following link:
https://apkpure.com/jptt-%E8%A1%8C%E5%8B%95%E8%A3%9D%E7%BD%AE%E4%B9%9F%E8%83%BD%E8%BC%95%E9%AC%86%E7%80%8F%E8%A6%BDptt/com.joshua.jptt

It detects as normal, but it works incorrectly.
![Screenshot_20200516-101644635](https://user-images.githubusercontent.com/9511279/82108048-932ad800-975e-11ea-84b7-6222feefd721.jpg)
