### ISSUE TITLE
Not enough space to show ad. Needs 360x50 dp, but only has 360x0 dp.

### ISSUE THREAD

**Issue by xuefer** [chiehmin/MinMinGuard#25]
when enabled for something like SSHDroid, logcat show massive with
W/Ads     ( 5335): Not enough space to show ad. Needs 360x50 dp, but only has 360x0 dp.

**Comment by chiehmin** [comment]
It's normal. I reset the height of ads to 0. Does it broke the layout?

**Comment by xuefer** [comment]
Layout is not broken but log flush ing by this message massively like no
tonorrow, it take CPU power. Block ad == power consume

**Comment by pylerSM** [comment]
So enable ads back, which doesn't take CPU power (sarcasm, sorry)
Seriously, there is so much logging in Android background so one log really can't break or improve battery life or so.

**Comment by xuefer** [comment]
sorry to hear that the side effect can't be avoided nor it be your concern.
Thanks anyway

**Comment by pylerSM** [comment]
Maybe fatminmin can try to "nullify" loadAd method.

I checked this log in Google and probably it is logged in onReceivedAd.
