### ISSUE TITLE
Ads in 2 apps still showing up

### ISSUE THREAD

**Issue by nchhajed** [chiehmin/MinMinGuard#37]
MinMinGuard 1.9.1 is working fine for my other existing apps but not for the 2 apps below:
1. Flightview Free
   Play Store Link: https://play.google.com/store/apps/details?id=com.flightview.flightview_free&hl=en
   Was working before but I believe they have new ad service. Ads are at the bottom.
   ![screenshot_2015-06-08-08-39-59](https://cloud.githubusercontent.com/assets/7421699/8036522/f4fd55e2-0dbd-11e5-92b2-a0d500ce3b26.png)
2. WallStreet Journal
   Play Store Link:https://play.google.com/store/apps/details?id=wsj.reader_sp&hl=en
   No idea why does WSJ show ad even for paid subscription :)
   ![screenshot_2015-06-08-02-10-11](https://cloud.githubusercontent.com/assets/7421699/8036539/1495d032-0dbe-11e5-8052-bd90b30e48b2.png)

**Comment by chiehmin** [comment]
Ok, I will take a look of this.
