### ISSUE TITLE
Spamming Xposed Log

### ISSUE THREAD

**Issue by yairh** [chiehmin/MinMinGuard#53]
Hello,

I was seeing a lot of unknown activity on my Xposed log lately, and thought to see if MinMinGuard has anything to do with it.
I saw that it's indeed spamming the logs, every time 'handleLoadPackage' is called.
Link to the problematic line: https://github.com/chiehmin/MinMinGuard/blob/master/app/src/main/java/tw/fatminmin/xposed/minminguard/Main.java#L116
Please fix this :)

Thanks a lot,
Yair

**Comment by chiehmin** [comment]
fixed
