### ISSUE TITLE
Advertisements of JPTT in version 2.20.4 (latest) can't be filtered with Minminguard 2.0.0 Alpha 3

### ISSUE THREAD

**Issue by Kara-ism** [chiehmin/MinMinGuard#57]
Hi.

Since I updated minminguard to 2.0.0 alpha 3 ,the ads in JPTT 2.20.4 ,which is the latest version ,aren't blocked;or it blocked with blank space left.

I have confirmed Xposed framework is applied and minminguard is enabled.

Here's the environment of my phone:
LG G Pro2 with offcial 4.4.2 ROM
Xposed 2.6
![screenshot_2015-10-26-11-40-18](https://cloud.githubusercontent.com/assets/9511279/10722121/b99cc3f0-7be7-11e5-80ab-c5f5fc1654d7.png)
![screenshot_2015-10-26-11-45-20](https://cloud.githubusercontent.com/assets/9511279/10722124/c39b53bc-7be7-11e5-8f9e-880421f444d3.png)

Any solutions of this situation? Thanks!

**Comment by chiehmin** [comment]
Thanks for report. I will resolve this problem ASAP.

**Comment by Kara-ism** [comment]
@chiehmin

JPTT is updated itself to 2.21;

However, it is also no prohibition in that version, and same circumstances occur on 台中等公車(nexti.android.bustaichung) series apps,developed by yapin.

**Comment by chiehmin** [comment]
Please update to alpha4. It should solve the JPTT problem.

**Comment by Kara-ism** [comment]
@chiehmin

It works again after updating to Alpha 4.
Thank you for taking so much time to fix this problem !!! :smile: :smile:
