### ISSUE TITLE
MangaDLR and AnimeDLR. Blank ad banner not hidden.

### ISSUE THREAD

**Issue by beepFTW** [chiehmin/MinMinGuard#65]
MangaDLR: https://cylonu87.wordpress.com/2015/10/26/mangadlr-3-4-0-15/
AnimeDLR: https://cylonu87.wordpress.com/2015/10/29/animedlr-0-0-2/

I use an alternative ad blocker to block the startapp fullscreen ads that appear on exit.
Banners are visible in all catalog views for both applications.

Thank you for the continued development!

**Comment by beepFTW** [comment]
Any idea?

**Comment by chiehmin** [comment]
I haven't have time to look into it. I will do it in the future. Be patient.
