### ISSUE TITLE
MinMinGuard does not work on Quick System Info Pro. 

### ISSUE THREAD

**Issue by YuriPL2** [chiehmin/MinMinGuard#7]
As in the topic. MinMinGuard is not able to remove ads form Quick System Info Pro. Screenshot:

![screenshot_2014-06-05-17-50-20](https://cloud.githubusercontent.com/assets/5256217/3189987/7c739b1a-ecc9-11e3-9b95-9481ea6a828d.png)

**Comment by chiehmin** [comment]
fixed in 1.9.0
