### ISSUE TITLE
Mobile01

### ISSUE THREAD

**Issue by adleavemealone** [chiehmin/MinMinGuard#70]
MinMinGuard 2.0 alpha 9 , AUTO mode , enable and disable Url filtering .

https://play.google.com/store/apps/details?id=com.mobile01.android.forum

開啟APP時會彈出廣告(並非每次開啟都會彈出) 以及出現在首頁的廣告。

謝謝。

**Comment by Kara-ism** [comment]
There's another way to bypass the ads of Mobile01 if you have root privilege of your android phone.
