### ISSUE TITLE
Weather Underground empty space not removed 

### ISSUE THREAD

**Issue by jimydirektsaft** [chiehmin/MinMinGuard#77]
https://play.google.com/store/apps/details?id=com.wunderground.android.weather
## First page in app

Empty space is not removed - 
MinMinGuard signals diverse blocked ads but empty space is not removed.

**Comment by chiehmin** [comment]
This should be solve by 527b2feae7c1ea8a503f2801019e310b10d6035c.

**Comment by chiehmin** [comment]
Ok, I saw the empty space in maps page.
