### ISSUE TITLE
YouBike (tw.com.sstc.youbike)

### ISSUE THREAD

**Issue by GeographicCone** [chiehmin/MinMinGuard#78]
It'd be great if you could add ad blocking for the YouBike app:
https://play.google.com/store/apps/details?id=tw.com.sstc.youbike

The ads shows up on the bottom of the station list screen and (from looking at the decompiled source) also somewhere else.

I generally avoid adware anyway (either buying the full version or going for an alternative) so this is the only thing I was hoping to use your module for because in this particular situation there's no other choice.

The app is crap though so please don't spend too much time on it, especially as the most important functionality is mirrored in the ad-free:
https://play.google.com/store/apps/details?id=tms.tw.governmentcase.taipeitranwell

I was just surprised that it's not already blocked since you seem to be from Taiwan too.
All the best,

**Comment by chiehmin** [comment]
Ok, I will take a look of it after my finals >"<

btw, I never use YouBike app though I used to ride YouBike everyday XD

**Comment by GeographicCone** [comment]
Wow, that was fast.
Thanks!

**Comment by Gitoffthelawn** [comment]
Good luck on your finals FatMinMin!

**Comment by chiehmin** [comment]
YouBike ad is removed by 03efbe5b148d36a8ef10e9b1c6efc4eca0ec6e40.

However, I cannot find ad in 台北好行. Can you show me where it is?

**Comment by GeographicCone** [comment]
Somehow never got to say thanks. The updates are working great of course, and YouBike ads are no more! Your work is really appreciated.

(In the previous post I meant to say 台北好行 can be used for YouBike without ads. I think it never had any advertising in it. Sorry I didn't write it clearly.)

Thanks again!
