### ISSUE TITLE
Not blocking Ads in Casper

### ISSUE THREAD

**Issue by bacevs** [chiehmin/MinMinGuard#84]
MinMinGuard (v2.0alpha10) is not blocking ads in [Casper](http://casper.io/)

Google LG Nexus 5
Android 6.0.1 (Pure Nexus ROM 6.0.1-20160203)
(Android Security Patch level: 1 January 2016) 
Xposed v80-sdk23-arm

Here is a snippet of [Logcat log](https://paste2.org/6MDWPXM8)

![dnvivk3](https://cloud.githubusercontent.com/assets/1433845/12865929/1f757f2c-cd10-11e5-8314-2f01a3d0e651.png) 
![rtuxzft](https://cloud.githubusercontent.com/assets/1433845/12865931/21ed311e-cd10-11e5-80f9-7536a0844f65.png)

**Comment by chiehmin** [comment]
Should be fixed by 57283e24176c9c8cba38856547e1b92a67b913d6

**Comment by bacevs** [comment]
Still not blocking

**Comment by bacevs** [comment]
Still not blocking
