### ISSUE TITLE
adblocking is not a moral crime:  privacy is NOT a commodity

### ISSUE THREAD

**Issue by cultixate** [chiehmin/MinMinGuard#9]
Kudos to you for helping users protect themselves from profoundly intimate violation.

privacy is NOT a commodity.  Treating it as such is a moral crime near the level of human trafficking.

when apps are offered free making them free helps the developer effect his will.  Until such time as developers honestly label apps as malware or the adware kind of malware to provoke an informed user consent discussion adblocking by any means will continue rightly

:)

**Comment by SnowGabe** [comment]
This is not a right place to post. You are writing about adblocking in general.
